FROM docker.elastic.co/elasticsearch/elasticsearch:5.2.2

#RUN rm -rf /etc/elasticsearch
#RUN ln -s /usr/share/elasticsearch/config /etc/elasticsearch

#RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install x-pack
#RUN /usr/share/elasticsearch/bin/plugin install shield

#RUN /usr/share/elasticsearch/bin/shield/esusers useradd es_admin -p admin1 -r admin
#RUN bin/shield/esusers useradd kibana4-server -r kibana4_server -p password



