version: '2'
services:
  elasticsearch:
    build: elasticsearch/
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  elasticsearch-initial-data:
    build: elasticsearch-initial-data/
    links:
      - kibana
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    dns: 8.8.8.8
    links:
      - elasticsearch
  jenkins:
    build: jenkins/
    dns: 8.8.8.8
    volumes:
      - ./jenkins/data/jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
