#elasticsearch.username: kibana4-server
#elasticsearch.password: password

server.name: kibana
server.host: "0"
#elasticsearch.username: es_admin
#elasticsearch.password: admin1
xpack.security.enabled: false
xpack.monitoring.enabled: false
xpack.graph.enabled: false
xpack.reporting.enabled: false


# Kibana is served by a back end server. This controls which port to use.
server.port: 5601

# The host to bind the server to.
server.host: "0"

# The Elasticsearch instance to use for all your queries.
elasticsearch.url: http://elasticsearch:9200

# preserve_elasticsearch_host true will send the hostname specified in `elasticsearch`. If you set it to false,
# then the host you use to connect to *this* Kibana instance will be sent.
elasticsearch.preserveHost: true


# Time in milliseconds to wait for Elasticsearch at Kibana startup before retrying
# startup_timeout: 5000

# Set to false to have a complete disregard for the validity of the SSL
# certificate.
#verify_ssl: true

# SSL for outgoing requests from the Kibana Server (PEM formatted)
# ssl_key_file: /path/to/your/server.key
# ssl_cert_file: /path/to/your/server.crt

# Set the path to where you would like the process id file to be created.
# pid_file: /var/run/kibana.pid

# If you would like to send the log output to a file you can set the path below.
# This will also turn off the STDOUT log output.
# log_file: ./kibana.log
# Plugins that are included in the build, and no longer found in the plugins/ folder
#bundled_plugin_ids:
# - plugins/dashboard/index
# - plugins/discover/index
# - plugins/doc/index
# - plugins/kibana/index
# - plugins/markdown_vis/index
# - plugins/metric_vis/index
# - plugins/settings/index
# - plugins/table_vis/index
# - plugins/vis_types/index
# - plugins/visualize/index
