#network.host: 0.0.0.0
#shield:
#  authc:
#    realms:
#      shield:
#        type: esusers
#        order: 0

#script.engine.groovy.inline.aggs: on
#script.engine.groovy.inline.search: on
#script.groovy.sandbox.enabled: true
#script.inline: on
#script.indexed: on